// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.API.Data;

namespace Quiz.APP.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("Quiz.API.Models.Answers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<string>("CorrectAnswer");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Quiz.API.Models.MultipleAnswers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstAnswer");

                    b.Property<bool>("FirstAnswerCorrect");

                    b.Property<string>("SecondAnswer");

                    b.Property<bool>("SecondAnswerCorrect");

                    b.Property<string>("ThirdAnswer");

                    b.Property<bool>("ThirdAnswerCorrect");

                    b.HasKey("Id");

                    b.ToTable("MultipleAnswers");
                });

            modelBuilder.Entity("Quiz.API.Models.MultipleQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MultipleAnswersId");

                    b.Property<string>("Question");

                    b.HasKey("Id");

                    b.HasIndex("MultipleAnswersId");

                    b.ToTable("MultileQuestions");
                });

            modelBuilder.Entity("Quiz.API.Models.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswersId");

                    b.Property<string>("Question");

                    b.HasKey("Id");

                    b.HasIndex("AnswersId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quiz.API.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BinaryMode");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Quiz.API.Models.MultipleQuestions", b =>
                {
                    b.HasOne("Quiz.API.Models.MultipleAnswers", "MultipleAnswers")
                        .WithMany()
                        .HasForeignKey("MultipleAnswersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Quiz.API.Models.Questions", b =>
                {
                    b.HasOne("Quiz.API.Models.Answers", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
